-- AlterTable
ALTER TABLE `Favorite` MODIFY `createdAt` DATETIME(3) NOT NULL DEFAULT (UTC_TIMESTAMP() + INTERVAL 3 HOUR);

-- AlterTable
ALTER TABLE `Image` MODIFY `createdAt` DATETIME(3) NOT NULL DEFAULT (UTC_TIMESTAMP() + INTERVAL 3 HOUR);

-- AlterTable
ALTER TABLE `Message` MODIFY `createdAt` DATETIME(3) NOT NULL DEFAULT (UTC_TIMESTAMP() + INTERVAL 3 HOUR);

-- AlterTable
ALTER TABLE `PasswordReset` MODIFY `createdAt` DATETIME(3) NOT NULL DEFAULT (UTC_TIMESTAMP() + INTERVAL 3 HOUR);

-- AlterTable
ALTER TABLE `Review` MODIFY `createdAt` DATETIME(3) NOT NULL DEFAULT (UTC_TIMESTAMP() + INTERVAL 3 HOUR);

-- AlterTable
ALTER TABLE `Transaction` MODIFY `createdAt` DATETIME(3) NOT NULL DEFAULT (UTC_TIMESTAMP() + INTERVAL 3 HOUR);
